name: Feature Request
description: Suggest an idea for this project
labels: feature

## Feature Summary
A clear and concise description of the feature.

## Expected Implementation
What you expect the feature to do or how it should behave.

## Reasoning for Feature
Why this feature would be useful or necessary.

## Additional Context
Add any other context about the feature here.
